# .github/workflows/push-notifier.yml

name: Scheduled Push Notifications

on:
  schedule:
    - cron: '* * * * *' # every minute
  workflow_dispatch: # allows manual trigger

jobs:
  ping-api:
    runs-on: ubuntu-latest

    steps:
      - name: Call notify users API securely
        env:
          TOKEN: ${{ secrets.SERVER_SECRET_TOKEN }}
        run: |
          curl -sS -i -X POST https://checkngo.netlify.app/api/notify \
            -H "Authorization: Bearer $TOKEN" \
            -H "Content-Type: application/json" \
            -d '{}'
